export type ResearchLevel = "High" | "Moderate" | "Low";
export type HiringLevel = "High" | "Stable" | "Low";
export type Trend = "up" | "flat" | "down";
export type CompanySize = "Startup" | "Scale-up" | "Enterprise";
export type Region = "North America" | "Europe" | "Asia Pacific";
export type GithubLevel = "Very High" | "High" | "Moderate" | "Low";

export interface CompanySummary {
  slug: string;
  name: string;
  logoLetter: string;
  tagline: string;
  momentumScore: number;
  growthRate: number;
  latestModelRelease: string;
  signalsThisWeek: number;
  researchActivity: ResearchLevel;
  hiringMomentum: HiringLevel;
  hiringTrend: Trend;
  techFocus: string[];
  fundingHeadline: string;
  fundingDate: string;
  foundedYear: number;
  industry: string;
  hqRegion: Region;
  companySize: CompanySize;
  modelsReleasedCount: number;
  githubActivityLevel: GithubLevel;
  isOpenSource: boolean;
  fundingAmountUSD: number;
  enterpriseAdoptionScore: number;
}

export const COMPANIES: CompanySummary[] = [
  {
    slug: "openai",
    name: "OpenAI",
    logoLetter: "O",
    tagline: "General Cognitive Intelligence Platforms",
    momentumScore: 96,
    growthRate: 38,
    latestModelRelease: "GPT-5",
    signalsThisWeek: 18,
    researchActivity: "High",
    hiringMomentum: "High",
    hiringTrend: "up",
    techFocus: ["LLMs", "Reasoning", "Agents", "Voice AI"],
    fundingHeadline: "$6.6B raised",
    fundingDate: "Oct 2024 round",
    foundedYear: 2015,
    industry: "General-Purpose AI / LLMs",
    hqRegion: "North America",
    companySize: "Enterprise",
    modelsReleasedCount: 6,
    githubActivityLevel: "High",
    isOpenSource: false,
    fundingAmountUSD: 6_600_000_000,
    enterpriseAdoptionScore: 92,
  },
  {
    slug: "anthropic",
    name: "Anthropic",
    logoLetter: "A",
    tagline: "Safety & Agentic Developer Environments",
    momentumScore: 97,
    growthRate: 45,
    latestModelRelease: "Claude 5",
    signalsThisWeek: 21,
    researchActivity: "High",
    hiringMomentum: "High",
    hiringTrend: "up",
    techFocus: ["LLMs", "AI Safety", "Agents", "Coding AI"],
    fundingHeadline: "$4B Amazon + $2B Google backing",
    fundingDate: "2024 rounds",
    foundedYear: 2021,
    industry: "AI Safety & Agentic Developer Platforms",
    hqRegion: "North America",
    companySize: "Enterprise",
    modelsReleasedCount: 6,
    githubActivityLevel: "Moderate",
    isOpenSource: false,
    fundingAmountUSD: 6_000_000_000,
    enterpriseAdoptionScore: 89,
  },
  {
    slug: "google-deepmind",
    name: "Google DeepMind",
    logoLetter: "G",
    tagline: "Scientific Breakthrough & Foundational Models",
    momentumScore: 93,
    growthRate: 22,
    latestModelRelease: "Gemini 3",
    signalsThisWeek: 16,
    researchActivity: "High",
    hiringMomentum: "Stable",
    hiringTrend: "flat",
    techFocus: ["LLMs", "Vision", "Science AI", "Robotics"],
    fundingHeadline: "Parent-Alphabet backed",
    fundingDate: "Ongoing",
    foundedYear: 2010,
    industry: "AI Research & Scientific Discovery",
    hqRegion: "Europe",
    companySize: "Enterprise",
    modelsReleasedCount: 5,
    githubActivityLevel: "High",
    isOpenSource: false,
    fundingAmountUSD: 75_000_000_000,
    enterpriseAdoptionScore: 88,
  },
  {
    slug: "meta-ai",
    name: "Meta AI",
    logoLetter: "M",
    tagline: "Open Weights & Decentralized Architectures",
    momentumScore: 91,
    growthRate: 19,
    latestModelRelease: "Llama 4",
    signalsThisWeek: 14,
    researchActivity: "High",
    hiringMomentum: "Stable",
    hiringTrend: "up",
    techFocus: ["LLMs", "Open Source", "Vision", "AR/VR"],
    fundingHeadline: "Parent-Meta backed",
    fundingDate: "Ongoing",
    foundedYear: 2013,
    industry: "Open-Source AI & Consumer Platforms",
    hqRegion: "North America",
    companySize: "Enterprise",
    modelsReleasedCount: 5,
    githubActivityLevel: "Very High",
    isOpenSource: true,
    fundingAmountUSD: 65_000_000_000,
    enterpriseAdoptionScore: 78,
  },
  {
    slug: "mistral",
    name: "Mistral",
    logoLetter: "M",
    tagline: "Efficient, Highly Parameter-dense Edge Models",
    momentumScore: 84,
    growthRate: 15,
    latestModelRelease: "Mistral Large 3",
    signalsThisWeek: 9,
    researchActivity: "Moderate",
    hiringMomentum: "Stable",
    hiringTrend: "flat",
    techFocus: ["LLMs", "Edge AI", "Coding AI"],
    fundingHeadline: "$640M raised",
    fundingDate: "Series B",
    foundedYear: 2023,
    industry: "Efficient LLMs & European Enterprise AI",
    hqRegion: "Europe",
    companySize: "Scale-up",
    modelsReleasedCount: 5,
    githubActivityLevel: "High",
    isOpenSource: true,
    fundingAmountUSD: 640_000_000,
    enterpriseAdoptionScore: 64,
  },
  {
    slug: "cursor",
    name: "Cursor (Anysphere)",
    logoLetter: "C",
    tagline: "AI-Augmented Developer Environments",
    momentumScore: 92,
    growthRate: 64,
    latestModelRelease: "Composer 2 Agent Engine",
    signalsThisWeek: 12,
    researchActivity: "Moderate",
    hiringMomentum: "High",
    hiringTrend: "up",
    techFocus: ["Coding AI", "Agents", "Developer Tools"],
    fundingHeadline: "$60M raised",
    fundingDate: "Series B",
    foundedYear: 2022,
    industry: "AI-Native Developer Tools",
    hqRegion: "North America",
    companySize: "Startup",
    modelsReleasedCount: 2,
    githubActivityLevel: "Low",
    isOpenSource: false,
    fundingAmountUSD: 60_000_000,
    enterpriseAdoptionScore: 76,
  },
  {
    slug: "perplexity",
    name: "Perplexity",
    logoLetter: "P",
    tagline: "AI-Driven Search & Information Indexing",
    momentumScore: 88,
    growthRate: 33,
    latestModelRelease: "Sonar 2 Search Model",
    signalsThisWeek: 11,
    researchActivity: "Moderate",
    hiringMomentum: "Stable",
    hiringTrend: "up",
    techFocus: ["Search AI", "LLMs", "Agents"],
    fundingHeadline: "$500M raised, $9B valuation",
    fundingDate: "2025 round",
    foundedYear: 2022,
    industry: "AI Search & Answer Engines",
    hqRegion: "North America",
    companySize: "Scale-up",
    modelsReleasedCount: 2,
    githubActivityLevel: "Low",
    isOpenSource: false,
    fundingAmountUSD: 500_000_000,
    enterpriseAdoptionScore: 55,
  },
  {
    slug: "microsoft-ai",
    name: "Microsoft AI",
    logoLetter: "M",
    tagline: "Enterprise Copilots & Agentic Productivity",
    momentumScore: 90,
    growthRate: 17,
    latestModelRelease: "Copilot Actions Agent Suite",
    signalsThisWeek: 15,
    researchActivity: "High",
    hiringMomentum: "Stable",
    hiringTrend: "flat",
    techFocus: ["Enterprise AI", "Agents", "LLMs", "Copilots"],
    fundingHeadline: "Parent-Microsoft backed, $13B OpenAI stake",
    fundingDate: "Ongoing",
    foundedYear: 2023,
    industry: "Enterprise AI & Cloud Platforms",
    hqRegion: "North America",
    companySize: "Enterprise",
    modelsReleasedCount: 3,
    githubActivityLevel: "Very High",
    isOpenSource: false,
    fundingAmountUSD: 13_000_000_000,
    enterpriseAdoptionScore: 96,
  },
  {
    slug: "xai",
    name: "xAI",
    logoLetter: "X",
    tagline: "Truth-Seeking Reasoning Models at Scale",
    momentumScore: 89,
    growthRate: 58,
    latestModelRelease: "Grok 5",
    signalsThisWeek: 13,
    researchActivity: "Moderate",
    hiringMomentum: "High",
    hiringTrend: "up",
    techFocus: ["LLMs", "Reasoning", "Real-time Data"],
    fundingHeadline: "$12B raised",
    fundingDate: "2025 round",
    foundedYear: 2023,
    industry: "Conversational AI & Real-Time Data",
    hqRegion: "North America",
    companySize: "Scale-up",
    modelsReleasedCount: 5,
    githubActivityLevel: "Moderate",
    isOpenSource: false,
    fundingAmountUSD: 12_000_000_000,
    enterpriseAdoptionScore: 42,
  },
  {
    slug: "deepseek",
    name: "DeepSeek",
    logoLetter: "D",
    tagline: "Efficient Training & Open Frontier Models",
    momentumScore: 86,
    growthRate: 71,
    latestModelRelease: "DeepSeek V4",
    signalsThisWeek: 10,
    researchActivity: "High",
    hiringMomentum: "Stable",
    hiringTrend: "up",
    techFocus: ["LLMs", "Efficient Training", "Open Source"],
    fundingHeadline: "Backed by High-Flyer Capital",
    fundingDate: "Self-funded",
    foundedYear: 2023,
    industry: "Open-Source Frontier Models",
    hqRegion: "Asia Pacific",
    companySize: "Startup",
    modelsReleasedCount: 4,
    githubActivityLevel: "Very High",
    isOpenSource: true,
    fundingAmountUSD: 0,
    enterpriseAdoptionScore: 60,
  },
  {
    slug: "cohere",
    name: "Cohere",
    logoLetter: "C",
    tagline: "Enterprise-Grade Language & Retrieval Models",
    momentumScore: 78,
    growthRate: 12,
    latestModelRelease: "Command R3",
    signalsThisWeek: 7,
    researchActivity: "Moderate",
    hiringMomentum: "Low",
    hiringTrend: "flat",
    techFocus: ["Enterprise AI", "LLMs", "RAG"],
    fundingHeadline: "$500M raised",
    fundingDate: "Series D",
    foundedYear: 2019,
    industry: "Enterprise NLP & Retrieval",
    hqRegion: "North America",
    companySize: "Scale-up",
    modelsReleasedCount: 4,
    githubActivityLevel: "Moderate",
    isOpenSource: false,
    fundingAmountUSD: 500_000_000,
    enterpriseAdoptionScore: 74,
  },
  {
    slug: "hugging-face",
    name: "Hugging Face",
    logoLetter: "H",
    tagline: "Open Source Model Hub & Tooling",
    momentumScore: 85,
    growthRate: 24,
    latestModelRelease: "Inference Endpoints 2.0",
    signalsThisWeek: 12,
    researchActivity: "High",
    hiringMomentum: "Stable",
    hiringTrend: "up",
    techFocus: ["Open Source", "Model Hub", "Developer Tools"],
    fundingHeadline: "$235M raised",
    fundingDate: "Series D",
    foundedYear: 2016,
    industry: "Open-Source AI Infrastructure",
    hqRegion: "North America",
    companySize: "Scale-up",
    modelsReleasedCount: 3,
    githubActivityLevel: "Very High",
    isOpenSource: true,
    fundingAmountUSD: 235_000_000,
    enterpriseAdoptionScore: 66,
  },
];
